export type DatabaseRowType = {
  orderId?: string;
  dateOfLive?: string;
  page?: string;
  liverName?: string;
  locationOfMiner?: string;
  minerName?: string;
  itemDescription?: string;
  grams?: number;
  source?: string;
  category?: string;
  mc?: number | string;
  goldRate?: number;
  supplierRate?: number | string;
  clientRate?: number;
  profit?: number | string;
  modeOfSale?: string;
  status?: string;
  modeOfPayment?: string;
  downpayment?: string;
  la1MonthPayment?: string;
  la2MonthPayment?: string;
  la3MonthPayment?: string;
  la4MonthPayment?: string;
  liverAdminRemarks?: string;
  dispatchDate?: string;
  deliveredDate?: string;
  reviewChasing?: string;
  fbProfileName?: string;
  regions?: string;
  remittanceStatus?: string;
  currency?: string;
  additionalCharges?: string;
  amountReceived?: string;
  freeSf?: string; // 'TRUE' | '' — stored as string in Google Sheets
  auditTrail?: string;
  tog?: string;
  pureWeight?: string;
  qty?: number;
  customerId?: string;
  invoiceNumber?: string;
  clientAddress?: string;
  clientNumber?: string;
  /** Position-independent row identity (see DATABASE_HEADERS.rowKey). */
  rowKey?: string;
  /** Zoho Invoice number assigned by Zoho (never generated by this app). */
  zohoInvoice?: string;
  /** Zoho customer id, so a client is never duplicated in their accounts. */
  zohoContactId?: string;
  id: number;
};

export type ClientGroup = {
  minerName: string;
  records: DatabaseRowType[];
};

export type TabProps = {
  /** Batched multi-row update — one API request instead of one per row. */
  onBulkUpdate?: (updates: { rowId: number; fields: Partial<DatabaseRowType> }[]) => Promise<void>;
  records: DatabaseRowType[];
  searchQuery: string;
  onSearchChange: (q: string) => void;
  onUpdate: (rowId: number, fields: Partial<DatabaseRowType>) => Promise<void>;
  userEmail?: string;
  userFirstName?: string;
  onRefresh?: () => void;
  lockedLiverName?: string; // Set for liver-role users — they can only see their own name
  /** Pre-computed client milestones (computed once in App.tsx) */
  clientMilestones?: Map<string, import('@/lib/milestones').ClientMilestone>;
};
