/**
 * Replacement for 'zite-endpoints-sdk'. The ported components call these
 * exact function names with the exact same param shapes as the real
 * src/api/*.ts endpoints -- this file just re-exports our Google Sheets
 * server actions under those same names so nothing else in the ported UI
 * code needs to change.
 */
export {
  getRecords,
  createRecord,
  updateRecord,
  bulkUpdateRecords,
  mergeClients,
  splitItem,
  generateInvoiceNumber,
  importRows,
  recordLastImport,
  getLastImport,
  undoLastImport,
  getUploads,
  createUpload,
  getRewardInventory,
  updateRewardInventory,
  getRoles,
  saveRatesConfig,
  getRatesConfig,
  getBrandSettings,
  saveBrandSettings,
  getBrandLogo,
  saveBrandLogo,
  getPageLogos,
  savePageLogo,
  deletePageLogo,
  verifyConnectionAndHeaders,
  getDataOptions,
  getPricingConfig,
  savePricingConfig,
  getTabConfig,
  saveTabConfig,
  getBusinessConfig,
  saveBusinessConfig,
  getLabelConfig,
  saveLabelConfig,
  getAppConfig,
  saveAppConfig,
  getMasterlistMapping,
  saveMasterlistMapping,
  getOptionsConfig,
  saveOptionsConfig,
  getCustomToggles,
  saveCustomToggles,
  backfillRowKeys,
  checkDatabaseColumns,
  fixDatabaseColumns,
  getMasterlistTemplate,
  saveMasterlistTemplate,
  clearMasterlistTemplate,
  getPurchases,
  createPurchase,
  updatePurchase,
  deletePurchase,
} from "./google-sheets/actions";

export type {
  GetRewardInventoryOutputType,
  RewardInventoryItem,
  RewardHistoryEntry,
  ConnectionCheckResult,
  TabHeaderCheck,
  DataOptions,
  PurchaseOrder,
  PageLogo,
  LastImportInfo,
} from "./google-sheets/actions";

export {
  getLiveData,
  saveLivePriceList,
  startLiveSession,
  finishLiveSession,
  deleteLiveSession,
  addLiveItems,
  updateLiveItems,
  addLiveStock,
  deleteLiveStock,
  addToLiveSession,
  transferLiveWeight,
  moveLiveItems,
  updateLiveSession,
  deleteLiveItems,
} from "./google-sheets/liveSellers";
export type { LiveItemInput } from "./google-sheets/liveSellers";
